module TestaAppiumDriver
  FIND_STRATEGY_UIAUTOMATOR = :uiautomator
  FIND_STRATEGY_XPATH = :xpath

  SCROLL_STRATEGY_UIAUTOMATOR = :uiautomator
  SCROLL_STRATEGY_W3C = :w3c

  SCROLL_CORRECTION_W3C = 45
  SCROLL_ALIGNMENT_THRESHOLD = 25

  SCROLL_ACTION_TYPE_SCROLL = :scroll
  SCROLL_ACTION_TYPE_FLING = :fling


  DEFAULT_FIND_STRATEGY = :uiautomator
  DEFAULT_W3C_MAX_SCROLLS = 7

  EXISTS_WAIT = 0.5
end